# Generated by Django 4.1.1 on 2022-10-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('text', models.TextField(verbose_name='Post Yazısı')),
                ('image', models.FileField(upload_to='post', verbose_name='Post Fotoğrafı')),
                ('new_date', models.DateTimeField(verbose_name='Paylaşma tarihi')),
            ],
        ),
    ]
