# Generated by Django 4.1.1 on 2022-10-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='new_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Paylaşma tarihi'),
        ),
    ]
