# Generated by Django 4.1.2 on 2022-10-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_post_new_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fiyat',
            field=models.IntegerField(default=1, verbose_name='fiyat'),
            preserve_default=False,
        ),
    ]
