# Generated by Django 4.1.2 on 2022-10-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_post_fiyat'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, verbose_name='Kullanıcı adı ')),
                ('password', models.CharField(max_length=200, verbose_name='Kullanıcı Şifre')),
            ],
        ),
    ]
