# Generated by Django 4.1.2 on 2022-10-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_sepet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepet',
            name='fiyat',
            field=models.FloatField(default=1, verbose_name='Toplam fiyat'),
            preserve_default=False,
        ),
    ]
